// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(408870530, name);
}

/**
 * Stop is called when the fx system is shutdown, used for graceful shutdown of components
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2507534237);
}
