// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db_types_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrator creates a new instance of MockMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrator {
	mock := &MockMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrator is an autogenerated mock type for the Migrator type
type MockMigrator struct {
	mock.Mock
}

type MockMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrator) EXPECT() *MockMigrator_Expecter {
	return &MockMigrator_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Down(ctx context.Context, version int64) error {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockMigrator_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - version int64
func (_e *MockMigrator_Expecter) Down(ctx any, version any) *MockMigrator_Down_Call {
	return &MockMigrator_Down_Call{Call: _e.mock.On("Down", ctx, version)}
}

func (_c *MockMigrator_Down_Call) Run(run func(ctx context.Context, version int64)) *MockMigrator_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrator_Down_Call) Return(err error) *MockMigrator_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Down_Call) RunAndReturn(run func(ctx context.Context, version int64) error) *MockMigrator_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockMigrator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrator_Expecter) Stop(ctx any) *MockMigrator_Stop_Call {
	return &MockMigrator_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockMigrator_Stop_Call) Run(run func(ctx context.Context)) *MockMigrator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrator_Stop_Call) Return(err error) *MockMigrator_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockMigrator_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Up(ctx context.Context, version *int64) error {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) error); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockMigrator_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - version *int64
func (_e *MockMigrator_Expecter) Up(ctx any, version any) *MockMigrator_Up_Call {
	return &MockMigrator_Up_Call{Call: _e.mock.On("Up", ctx, version)}
}

func (_c *MockMigrator_Up_Call) Run(run func(ctx context.Context, version *int64)) *MockMigrator_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrator_Up_Call) Return(err error) *MockMigrator_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Up_Call) RunAndReturn(run func(ctx context.Context, version *int64) error) *MockMigrator_Up_Call {
	_c.Call.Return(run)
	return _c
}
